name: Mixed inputs with Build

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - VARSHINI
        - AADVIK
      message:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      with:
        repository: ${{ github.event.inputs.message }} 
        ref: ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} 
        path: ${{ github.event.inputs.name }}"

  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v3
      - name: Environment settings interface
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          path: ${{ github.event.repository.name }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
