name: Build Command
on:
  repository_dispatch:
    types: [build-command]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the pull request branch
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}
          path: ${{ github.event.repository.name }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
